### ISSUE TITLE
Standardize plugin naming conventions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-plugins#10]
Dashboard plugins are non-dashboard plugins are following different naming conventions. Plugin names, folder names, architecture naming and artifact naming should be consistent for all plugins, regardless of what kinds of plugins they are.

For dashboards this was enforced in 7.7 [here](https://www.elastic.co/guide/en/kibana/7.7/breaking-changes-7.7.html#_enforce_camelcase_format_for_a_plugin_id), PR [here](https://github.com/elastic/kibana/pull/53759).

**Comment by stockholmux** [comment]
This drives me nuts. This may echo a Javascript/TypeScript style, avoiding translating what is reference in source to a filename, which makes _some_ sense.

**Comment by saratvemulapalli** [comment]
Updated this issue to track all items for naming conventions across plugins.
We can work on a doc once these items are cemented!

- [ ] Artifacts
- [ ] Classes
- [ ] APIs
- [ ] Indices
- [ ] Identifiers
- [ ] Variables

**Comment by ohltyler** [comment]
Proposed a fix in [this issue](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/322) on Dashboards last week which could unblock automating this rename process and allow for easily changing the plugin name and folder to be consistent with OpenSearch plugins (in other words, not camel case).

The plugin id itself used by the Dashboards platform will be a more complex fix as it is "part of the plugin contract" as mentioned [here](https://github.com/elastic/kibana/blob/master/docs/development/core/server/kibana-plugin-core-server.pluginmanifest.md#properties) and will have a lot more implications when changing this.

**Comment by cliu123** [comment]
A template of the naming convention for class, method and variable, [ES plugins](https://github.com/elastic/elasticsearch/tree/5baabff6670a8ed49297488ca8cac8ec12a2078d/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authc/ldap) do not have prefixes.

**Comment by cliu123** [comment]
> This is part of #12.

@dblock The scope of this issue looks closer to the naming convention for method, class and variable. 
@dblock @saratvemulapalli Replacing `kibana`/`opendistro` with `openSearchDashboards`/`openSearch` VS. Removing  the prefixes. Is it necessary to impose commen naming conventions to all plugins? If not, plugins can decide to go with whatever approaches that make more sense.

**Comment by cliu123** [comment]
> Updated this issue to track all items for naming conventions across plugins.
> We can work on a doc once these items are cemented!
> 
> * [ ]  Artifacts
> * [ ]  Folder name
> * [ ]  Classes
> * [ ]  APIs
> * [ ]  Indices
> * [ ]  Identifiers
> * [ ]  Variables

@saratvemulapalli We have more to rename, for example, namespace(`com.amazon.opendistroforelasticsearch`), settings, etc.

**Comment by dblock** [comment]
I merged https://github.com/opensearch-project/opensearch-plugins/pull/19, which brought in https://github.com/opensearch-project/opensearch-plugins/blob/main/CONVENTIONS.md. Please contribute more conventions to this document!
