### ISSUE TITLE
Upgrade to Gradle 7

### ISSUE THREAD

**Issue by reta** [opensearch-project/opensearch-plugins#107]
**Is your feature request related to a problem?**
The OpenSearch Plugins are still built using Gradle 6.6.x whereas the Gradle release train has moved to 7.x already. The OpenSearch core is about to be switched to Gradle 7.3 (see please https://github.com/opensearch-project/OpenSearch/pull/1609), it would make sense to switch all plugins to Gradle 7.3 as well.

**What solution would you like?**
Update Gradle to 7.3

**What alternatives have you considered?**
N/A

**Do you have any additional context?**
See please https://github.com/opensearch-project/OpenSearch/issues/1246

- [ ] https://github.com/opensearch-project/data-prepper/issues/662
- [x] https://github.com/opensearch-project/alerting/issues/246
- [x] https://github.com/opensearch-project/anomaly-detection/issues/326
- [x] https://github.com/opensearch-project/asynchronous-search/issues/70
- [x] https://github.com/opensearch-project/dashboards-notebooks/issues/105
- [x] https://github.com/opensearch-project/dashboards-reports/issues/234
- [x] https://github.com/opensearch-project/index-management/issues/204
- [x] https://github.com/opensearch-project/job-scheduler/issues/104
- [x] https://github.com/opensearch-project/k-NN/issues/230
- [x] https://github.com/opensearch-project/performance-analyzer/issues/92
- [x] https://github.com/opensearch-project/security/issues/1505
- [x] https://github.com/opensearch-project/sql/issues/303
- [x] https://github.com/opensearch-project/trace-analytics/issues/278
- [x] https://github.com/opensearch-project/cross-cluster-replication/issues/259
- [x] https://github.com/opensearch-project/common-utils/issues/101

**Comment by dblock** [comment]
Added this issue to 1.3.0 campaigns, https://github.com/opensearch-project/opensearch-build/issues/889

**Comment by jmazanec15** [comment]
Getting a [failure](https://github.com/opensearch-project/k-NN/runs/4401833437?check_suite_focus=true) related to GlobalBuildInfoPlugin with Java 14 for [k-NN upgrade PR](https://github.com/opensearch-project/k-NN/pull/232):
```
* What went wrong:
A problem occurred evaluating root project 'opensearch-knn'.
> Failed to apply plugin class 'org.opensearch.gradle.info.GlobalBuildInfoPlugin'.
   > Could not create plugin of type 'GlobalBuildInfoPlugin'.
      > Could not generate a decorated class for type GlobalBuildInfoPlugin.
         > org/gradle/jvm/toolchain/JavaInstallation
```

Anyone else run into this?

**Comment by reta** [comment]
@jmazanec15 yes, the plugin uses 1.3.0-SNAPSHOT which is not yet on Gradle 7, the PR https://github.com/opensearch-project/OpenSearch/pull/1622 is not merged yet :(

**Comment by dlvenable** [comment]
Here are instructions for updating a project to Gradle 7:

0. You can try to fix Gradle 7 errors in your project before any update. Run your build with the `--warning-mode all` flag. Fix issues your your build files.

```
./gradlew --warning-mode all clean build
```

1. Run the Gradle wrapper task to update:

```
./gradlew wrapper --gradle-version 7.3
```

2. Add the OpenSearch snapshot repository to your `buildscript` `repositories` list. It may already be included.

```
maven { url 'https://aws.oss.sonatype.org/content/repositories/snapshots/' }
```

3. Update the OpenSearch `build-tools` dependency to the correct version. Right now, this change is only available in the 2.0.0-SNAPSHOT build.

```
classpath 'org.opensearch.gradle:build-tools:2.0.0-SNAPSHOT'
```

4. Run your build as usual.

**Configuration snippet for reference:**

```
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' }
        mavenCentral()
        maven { url 'https://aws.oss.sonatype.org/content/repositories/snapshots/' }
    }

    dependencies {
        classpath 'org.opensearch.gradle:build-tools:2.0.0-SNAPSHOT'
    }
}
```

**Comment by reta** [comment]
@dblock could you please add `2.0` label to this issue and remove `1.3.0`? Thank you.

**Comment by dblock** [comment]
@dlvenable says _Data Prepper cannot update to Gradle 7 until after OpenSearch 2.0 releases. Retaining Gradle 6 in Data Prepper does not block OpenSearch 2.0 or cause any sort of incompatibility between Data Prepper and OpenSearch._ I am going to close this for 2.0.0.
