### ISSUE TITLE
Remove support for Java 8

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-plugins#110]
**Is your feature request related to a problem?**

Because Apache [Lucene 9 requires JDK 11 or newer](https://cwiki.apache.org/confluence/display/LUCENE/Release+Notes+9.0), remove support for Java 8.

**Do you have any additional context?**

In https://github.com/opensearch-project/opensearch-plugins/issues/64 we ensured OpenSearch 1.x support for Java 8, 11, and 17, shipping with bundled JDK17. For 2.0 remove support for Java 8
### OpenSearch

- [x] https://github.com/opensearch-project/OpenSearch/pull/1368
- [x] https://github.com/opensearch-project/OpenSearch/pull/1609
- [x] https://github.com/opensearch-project/OpenSearch/issues/1689

### Plugins

- [x] https://github.com/opensearch-project/opensearch-plugins/issues/107
- [x] https://github.com/opensearch-project/alerting/issues/325
- [x] https://github.com/opensearch-project/anomaly-detection/issues/398
- [x] https://github.com/opensearch-project/asynchronous-search/issues/100
- [x] https://github.com/opensearch-project/common-utils/issues/124
- [x] https://github.com/opensearch-project/dashboards-reports/issues/301
- [x] https://github.com/opensearch-project/index-management/issues/289
- [x] https://github.com/opensearch-project/job-scheduler/issues/136
- [x] https://github.com/opensearch-project/k-NN/issues/311
- [x] https://github.com/opensearch-project/performance-analyzer/issues/154
- [x] https://github.com/opensearch-project/performance-analyzer-rca/issues/141
- [x] https://github.com/opensearch-project/security/issues/1669
- [x] https://github.com/opensearch-project/sql/issues/466
- [x] https://github.com/opensearch-project/observability/issues/547
- [x] https://github.com/opensearch-project/cross-cluster-replication/issues/330

**Comment by dblock** [comment]
@reta @dvenable @martin-gaievski is https://github.com/opensearch-project/k-NN/issues/220#issuecomment-1023677176 the only reason why we're dropping JDK 8 in 2.0? We should provide a strong(er) justification above.

**Comment by reta** [comment]
@dblock I think the only reason would be [1], since Apache Lucene 9.0 is setting JDK-11 baseline.

[1] https://github.com/opensearch-project/OpenSearch/pull/1109

**Comment by dblock** [comment]
> @dblock I think the only reason would be [1], since Apache Lucene 9.0 is setting JDK-11 baseline.
> 
> [1] [opensearch-project/OpenSearch#1109](https://github.com/opensearch-project/OpenSearch/pull/1109)

Right on. I updated the issue.

**Comment by dblock** [comment]
I've started drafting a blog post, please contribute! 

https://github.com/opensearch-project/project-website/pull/670
