### ISSUE TITLE
Drop support for JDK 14

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-plugins#132]
**Is your feature request related to a problem?**

In OpenSearch 1.3.0 we stopped testing the complete distribution with JDK 15 in favor of 11, so we can't make claims on compatibility with JDK 15. Plugins never built with JDK15 individually. 

The easiest thing to do is probably to just re-add JDK15 to CI matrices so that we can reclaim this compatibility. 

But we could also drop JDK 14.

**What solution would you like?**

Re-add JDK15 to the CI matrix.

or

Remove JDK14 from the CI matrix.

**Update: we decided to drop support for JDK 14**

- [x] https://github.com/opensearch-project/alerting/issues/374
- [x] https://github.com/opensearch-project/anomaly-detection/issues/479
- [x] https://github.com/opensearch-project/asynchronous-search/issues/121
- [x] https://github.com/opensearch-project/common-utils/issues/147
- [x] https://github.com/opensearch-project/dashboards-reports/issues/326
- [x] https://github.com/opensearch-project/index-management/issues/317
- [x] https://github.com/opensearch-project/job-scheduler/issues/158
- [x] https://github.com/opensearch-project/k-NN/issues/342
- [x] https://github.com/opensearch-project/performance-analyzer/issues/174
- [x] https://github.com/opensearch-project/performance-analyzer-rca/issues/151
- [x] https://github.com/opensearch-project/security/issues/1718
- [x] https://github.com/opensearch-project/sql/issues/522
- [x] https://github.com/opensearch-project/observability/issues/615
- [x] https://github.com/opensearch-project/cross-cluster-replication/issues/346

**Comment by dblock** [comment]
@dlvenable Want to comment on whether we should be dropping 14 instead of adding 15?

**Comment by dlvenable** [comment]
Why would anybody run against either JDK 14 or 15? The only reason I can is that these were (until recently) the "official" versions of OpenSearch. So some users may have decided to run on these JDKs and may have installed them on their clusters.

I suggest that starting in 2.0, OpenSearch only claims compatibility with LTS versions (11 and 17 presently).

It would be valuable to run tests against the latest version of non-LTS Java in order to catch issues which may arise. It could be nice to know that OpenSearch stops working with, say JDK 19.

**Comment by peternied** [comment]
From a resourcing perspective, I vote for _Remove JDK14 from the CI_

**Comment by dlvenable** [comment]
I agree with the vote _Remove JDK14 from the CI matrix._.

There may be value to keeping it in 1.x since it has been supported in OpenSearch 1.x. But I certainly think there is no reason to test 14 or 15 in 2.x.

**Comment by vamsi-amazon** [comment]
I agree with vote _Remove JDK14 from the CI matrix._ Similar to the lines of Java, Opensearch should be compatible with LTS versions JDK11 and JDK17.

**Comment by ylwu-amzn** [comment]
I think we should keep in 1.x for better backward compatibility. We can remove JDK14 from 2.0 as big version can tolerate some breaking change.

**Comment by peternied** [comment]
Its been a week now, I do not see any opinions suggesting that we add support for JDK15, making this a once sided issue. @dblock was there any other channels you wanted to get feedback from before we make a decision?

**Comment by dblock** [comment]
I'd like public comment, but I am waiting on https://github.com/opensearch-project/project-website/pull/670 to be published to ask.

**Comment by reta** [comment]
+1 to Remove JDK14 from the CI matrix.

**Comment by dblock** [comment]
Looks like no votes for keeping JDK14. I'm updating the issue and creating sub-issues in projects.
