### ISSUE TITLE
[FEATURE] Add Readme doc with details about gradle custom plugins.

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-plugins#143]
### Is your feature request related to a problem?
Right now we have multiple gradle custom build plugins for different problems, but no doc thats explains some background and plugin usage.

Associated issues:
https://github.com/opensearch-project/opensearch-build/issues/1916

### What solution would you like?
Create a `GRADLE_CUSTOM_PLUGINS.md` doc and add as much as details as possible.

**Comment by owaiskazi19** [comment]
@prudhvigodithi can we close this issue as the PR is merged?

**Comment by prudhvigodithi** [comment]
Hey @owaiskazi19 yes, this issue can closed.
Thank you
