### ISSUE TITLE
[CAMPAIGN] Bump jackson and snakeyaml dependencies

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-plugins#168]
Core has bumped jackson and snakeyaml dependencies to `2.13.4` and `1.32` respectively [here](https://github.com/opensearch-project/OpenSearch/pull/4556) for versions 2.x, 2.3 , 2.2 , 2.1 , 2.0, 1.3 and 1.x. Plugin and client teams should do the same to align with core for avoiding version conflicts.

What are you proposing? What do you suggest we do to solve the problem or improve the existing situation?

- [x] https://github.com/opensearch-project/data-prepper/issues/1839
- [x] https://github.com/opensearch-project/alerting/issues/580
- [x] https://github.com/opensearch-project/anomaly-detection/issues/676
- [x] https://github.com/opensearch-project/asynchronous-search/issues/189
- [x] https://github.com/opensearch-project/index-management/issues/525
- [x] https://github.com/opensearch-project/job-scheduler/issues/244
- [x] https://github.com/opensearch-project/k-NN/issues/566
- [x] https://github.com/opensearch-project/performance-analyzer/issues/288
- [x] https://github.com/opensearch-project/security/issues/2124
- [x] https://github.com/opensearch-project/sql/issues/869
- [x] https://github.com/opensearch-project/observability/issues/1053
- [x] https://github.com/opensearch-project/cross-cluster-replication/issues/569
- [x] https://github.com/opensearch-project/common-utils/issues/257
- [x] https://github.com/opensearch-project/opensearch-java/issues/227
- [x] https://github.com/opensearch-project/dashboards-reports/issues/478

**Comment by bbarani** [comment]
@sean-zheng-amazon @joshuali925 Can you please update the status of this issue?

**Comment by owaiskazi19** [comment]
Looks like all the tasks have been taken care of. Closing this campaign.
