### ISSUE TITLE
[DOC] Update the CONVENTIONS.md with solid guidance of plugin naming convention

### ISSUE THREAD

**Issue by ruanyl** [opensearch-project/opensearch-plugins#200]
For the team that is new to the plugin development, the current documentation of **repo name** and **package name** naming convention is a bit unclear.

It would be nice to add clarifications on the naming conventions of:
1. GitHub repo name of OpenSearch/OpenSearch-Dashboards plugin
2. Package name of OpenSearch-Dashboards plugin (`name` in `package.json`)

**Comment by dblock** [comment]
👍 please help contribute a PR! you might find https://github.com/opensearch-project/opensearch-plugins/issues/174 relevant

**Comment by ruanyl** [comment]
Hi @dblock @joshuarrrr, drafting a PR for it https://github.com/opensearch-project/opensearch-plugins/pull/204

Based on the current documentation and my observations, the dashboard plugin **repo name** should have prefix `dashboards`, however, the **plugin name and id** generally have `dashboards` as suffix. Do you see this as misalignment due to historical reason or was it by intention?

**Comment by dblock** [comment]
Resolved via https://github.com/opensearch-project/opensearch-plugins/pull/204
