### ISSUE TITLE
[Refactor] XContent from common to core namespace

### ISSUE THREAD

**Issue by nknize** [opensearch-project/opensearch-plugins#212]
XContent namespace refactor from common -> core is going to be merged to opensearch/2.x which will break the 2.x build.  This issue is for refactoring XContent imports from the `common` to `core` namespace after the core namespace change is merged.

Depends on https://github.com/opensearch-project/OpenSearch/pull/6470

**Comment by nknize** [comment]
https://github.com/opensearch-project/OpenSearch/pull/6470 merged

**Comment by DarshitChanpura** [comment]
Hey team, Is the still on-track for being merged for 2.7? The code-freeze for `v2.7.0` is on Apr 17.

**Comment by dblock** [comment]
@DarshitChanpura looks like it per https://github.com/opensearch-project/OpenSearch/issues/6841#issuecomment-1509079524

**Comment by mch2** [comment]
no reply, closing as 2.7 has shipped with this change.
