### ISSUE TITLE
[BUG] IntegTests fail for plugins when running them on non linux machine

### ISSUE THREAD

**Issue by AmiStrn** [opensearch-project/opensearch-plugins#40]
As mentioned in the [`BUILDING.md`](https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#L14)
> Please note that the limitation for integration tests is that it is only supported for builds on linux platform.

Reproduce by trying to run `./gradlew :integtest`. This will result in:
```
> Task :integTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':integTest'.
> Could not resolve all files for configuration ':opensearch_distro_extracted_testclusters--integTest-0-1.0.0-beta1-'.
   > Could not resolve opensearch-distribution:opensearch:1.0.0-beta1.
     Required by:
         project :
      > Could not resolve opensearch-distribution:opensearch:1.0.0-beta1.
         > Could not get resource 'https://artifacts.opensearch.org/releases/core/opensearch/1.0.0-beta1/opensearch-1.0.0-beta1-darwin-x64.tar.gz'.
            > Could not HEAD 'https://artifacts.opensearch.org/releases/core/opensearch/1.0.0-beta1/opensearch-1.0.0-beta1-darwin-x64.tar.gz'. Received status code 403 from server: Forbidden
```
Tested the [Asynchronous search](https://github.com/opensearch-project/asynchronous-search) integtests on: 
- macOS BigSur 
- version 11.2.1

---

Although it is mentioned that this is expected behavior I do think this is a bug, and should not be a caveat.

**Comment by saratvemulapalli** [comment]
Closing this in favor of the master issue.
