### ISSUE TITLE
Use AWS OSS Maven -SNAPSHOT for plugin dependencies

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-plugins#45]
Plugins should not build off OpenSearch/plugins for every build. 

See https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#building-within-the-opensearch-build-system for picking up dependencies from Maven.

- [x] https://github.com/opensearch-project/common-utils/issues/75
       https://github.com/opensearch-project/common-utils/pull/77
- [x] https://github.com/opensearch-project/alerting/issues/183
        https://github.com/opensearch-project/alerting/pull/184
- [x] https://github.com/opensearch-project/anomaly-detection/issues/242
- [x] https://github.com/opensearch-project/asynchronous-search/issues/45
- [x] https://github.com/opensearch-project/dashboards-notebooks/issues/88
- [x] https://github.com/opensearch-project/dashboards-reports/issues/179
- [x] https://github.com/opensearch-project/dashboards-visualizations/issues/29
- [x] https://github.com/opensearch-project/job-scheduler/pull/68
- [x] https://github.com/opensearch-project/performance-analyzer/pull/71
- [x] https://github.com/opensearch-project/performance-analyzer-rca/pull/82
- [x] https://github.com/opensearch-project/security/issues/1466
- [x] https://github.com/opensearch-project/sql/issues/219
- [x] https://github.com/opensearch-project/k-NN/issues/106
- [x] https://github.com/opensearch-project/index-management/issues/155
        https://github.com/opensearch-project/opensearch-build/issues/663

**Comment by ylwu-amzn** [comment]
Is this the goal of GA release?

**Comment by joshuali925** [comment]
@dblock any eta on when plugins can start this?

**Comment by saratvemulapalli** [comment]
> @dblock any eta on when plugins can start this?

@mch2 is working on it.

**Comment by mch2** [comment]
Plugins can start updating their scripts to depend on 1.0 artifacts from central.

If a snapshot of an unreleased version is desired you can add https://aws.oss.sonatype.org/content/repositories/snapshots/ to your list of repositories.  This is where nightly builds are being pushed of 1.0 and 1.x.

**Comment by dblock** [comment]
Someone needs to pickup a task of upgrading an existing plugin to use maven -SNAPSHOT dependencies for 1.1, make sure it works, and then open an issue in every repo to do the same.

**Comment by abbashus** [comment]
> Someone needs to pickup a task of upgrading an existing plugin to use maven -SNAPSHOT dependencies for 1.1, make sure it works, and then open an issue in every repo to do the same.

I'll pick this up

**Comment by dblock** [comment]
https://github.com/opensearch-project/data-prepper/pull/243/files

**Comment by dbbaughe** [comment]
https://github.com/opensearch-project/index-management/pull/141

**Comment by saratvemulapalli** [comment]
For all plugins who are onboarding to Maven, please continue to list `mavenlocal()` as one of the repositories. 
Pasting the comment from: https://github.com/opensearch-project/index-management/pull/141/files#r706333121

"As part of the CI/CD we are trying to run integration/bwc tests which qualifies the bundle and allows the maven artifacts to be published.
It would rely on `mavenlocal()` to run these tests."

**Comment by dblock** [comment]
Changing the label for 1.2. We need to update https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md, open an issue in every plugin and make sure this is closed. Who wants to take that on?

**Comment by abbashus** [comment]
@dblock yes I still own this. Will start in a couple of days.

**Comment by abbashus** [comment]
| Plugin                                                                           	| Issue                                     	| PR                                      	|
|----------------------------------------------------------------------------------	|-------------------------------------------	|-----------------------------------------	|
| [index-management](https://github.com/opensearch-project/index-management)       	| opensearch-project/index-management#155   	| opensearch-project/index-management#141 	|
| [alerting](https://github.com/opensearch-project/alerting)                       	| opensearch-project/alerting#183           	|                                         	|
| [asynchronous-search](https://github.com/opensearch-project/asynchronous-search) 	| opensearch-project/asynchronous-search#45 	|                                         	|
| [anomaly-detection](https://github.com/opensearch-project/anomaly-detection)     	| opensearch-project/anomaly-detection#242  	|                                         	|
| [index-management](https://github.com/opensearch-project/k-NN)                   	| opensearch-project/k-NN#106               	|                                         	|
| [sql](https://github.com/opensearch-project/sql)                                 	| opensearch-project/sql#219                	|                                         	|
| [common-utils](https://github.com/opensearch-project/common-utils)               	| opensearch-project/common-utils#75        	|                                         	|

**Comment by dblock** [comment]
- https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md needs to be updated
- plugins have to preserve `mavenLocal` on top of the list (local, aws sonatype, central is probably the right order) otherwise bundle build will become unreliable

**Comment by dblock** [comment]
I updated the top of this ticket with a complete list of projects that need to do this.

**Comment by CEHENKLE** [comment]
All tickets closed :)

**Comment by dblock** [comment]
Verified via meta, found 3 occurrences. Not sure whether these are used, and I know notifications doesn't ship with 1.2. Reopening to fix and re-confirm. 

```
meta exec "git checkout 1.2"
find . -type f -regex '.*/\.github\/workflows\/.*.yml' | xargs grep "'opensearch-project/OpenSearch'"

./dashboards-notebooks/.github/workflows/opensearch-notebooks-test-and-build-workflow.yml:          repository: 'opensearch-project/OpenSearch'
./security-dashboards-plugin/.github/workflows/integration-test.yml:          repository: 'opensearch-project/OpenSearch'
./notifications/.github/workflows/notifications-test-and-build-workflow.yml:          repository: 'opensearch-project/OpenSearch'
osx ~/source/opensearch-project/opensearch-build/opensearch-project/meta (main)$ 
```

- https://github.com/opensearch-project/dashboards-notebooks/issues/98
- https://github.com/opensearch-project/security-dashboards-plugin/issues/859
- https://github.com/opensearch-project/notifications/issues/365

**Comment by anirudha** [comment]
Notebooks and notifications are not part of 1.2

**Comment by dblock** [comment]
Looks like dashboards-notebooks is going to get archived, https://github.com/opensearch-project/dashboards-notebooks/issues/98#issuecomment-967272997

**Comment by dblock** [comment]
Spot checked again, https://github.com/opensearch-project/security-dashboards-plugin/pull/860 still needs to be backported to 1.2 to close this.

**Comment by peterzhuamazon** [comment]
@saratvemulapalli @dblock is this task consider complete? This is the only issue labeled as enhancement within 1.2.0.

**Comment by dblock** [comment]
I don’t see any mention of a backport for https://github.com/opensearch-project/security-dashboards-plugin/pull/860 so that needs to be tracked down.
