### ISSUE TITLE
Add test coverage reporting

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-plugins#46]
Add test coverage for unit and integration test reporting for all plugins.

**Comment by saratvemulapalli** [comment]
Linking the task from OpenSearch: https://github.com/opensearch-project/OpenSearch/issues/850

**Comment by tlfeng** [comment]
Currently all the plugins that has got code coverage reporting are using [JaCoCo](https://github.com/jacoco/jacoco) to generate the code coverage report, and using [Codecov](https://about.codecov.io/) for analysis and visualization.

**Comment by ylwu-amzn** [comment]
Is it enough to show test coverage percent on plugin readme doc?

**Comment by saratvemulapalli** [comment]
@ylwu-amzn yes that should be good for now, looks like most plugins have a badge which is used.

**Comment by saratvemulapalli** [comment]
Closing this as @tlfeng merged the changes to the repo.
