### ISSUE TITLE
Ensure branch protection rules across all plugin repos

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-plugins#52]
At least require 1 CR.

<img width="977" alt="Screen Shot 2021-06-14 at 9 58 18 AM" src="https://user-images.githubusercontent.com/542335/121904433-2c784500-ccf7-11eb-8c15-fb1e56183d29.png">

<strike>@hyandell Is there a way to do this for the org?</strike> doesn't look like it

**Comment by ylwu-amzn** [comment]
Do we need special permission to add "Branch protection rule" ? From this https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule, should see "Branches" when open settings page. But I can't see it when open AD settings.

**Comment by VijayanB** [comment]
@dblock Since none of the plugin owners are not part of admin, can someone from https://github.com/orgs/opensearch-project/teams/admin/members do this ?

**Comment by dblock** [comment]
> @dblock Since none of the plugin owners are not part of admin, can someone from https://github.com/orgs/opensearch-project/teams/admin/members do this ?

Yep, looks like we will have to do that. I'll figure out a script to do this across repos at some point soon.

**Comment by CEHENKLE** [comment]
All repos in opensearch-org now require at least 1 code review except:
logstash-output-opensearch
opensearch-infra
.github
opensearch-devops
opensearch-plugin-template-java

**Comment by ylwu-amzn** [comment]
> All repos in opensearch-org now require at least 1 code review

Maybe I missed something. What's that code review about? Should plugin owners prepare and send out that code review?

**Comment by CEHENKLE** [comment]
@ylwu-amzn Hey -- so branch protection is a setting per repo (you can learn more here:  https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule)  I've now set on all the repos minus the ones listed above a rule that requires at least one code review before merge.

So there's nothing for you to do except verify that the rule is working.  If you can merge with out a CR, then I made a mistake and will need to go back and check again.

Make sense?

Thanks!
/C

**Comment by ylwu-amzn** [comment]
Got it. Thanks. Will confirm if AD can work.
