### ISSUE TITLE
Ensure public documentation for plugins is updated

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-plugins#57]
Standardize the process of documenting new changes in plugins to opensearch-plugins/STANDARDS.md

**Comment by hsiang9431-amzn** [comment]
do we have an example for STANDARDS.md?

**Comment by saratvemulapalli** [comment]
> do we have an example for STANDARDS.md?

Should have been more clear. This will be documented to help guide on how to add public documentation. STANDARDS.md will live in opensearch-plugins repository. You dont have to replicate this file in the plugins.
