### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-plugins#58]
Add documentation support to have release notes standardized for all plugins

**Comment by saratvemulapalli** [comment]
Doc to release notes: https://github.com/opensearch-project/opensearch-plugins/blob/main/RELEASE_NOTES.md

**Comment by VijayanB** [comment]
@saratvemulapalli  Can you confirm whether all plugins should have this corresponding file in their repository or we just need to ensure we follow this process?

**Comment by saratvemulapalli** [comment]
Its just a standard process and how release notes should look like. 
You dont need to have similar files replicated in all the plugins.

**Comment by saratvemulapalli** [comment]
Closing this as we have added information on how release notes should be via: https://github.com/opensearch-project/opensearch-plugins/blob/main/STANDARDS.md#release-notes
