### ISSUE TITLE
[Proposal] Upgrading documentation warning about removed packages

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/opensearch-plugins#63]
Perhaps this location is the best place for this information: https://github.com/opensearch-project/opensearch-plugins/blob/main/UPGRADING.md

From the branch and purifying stage, the OpenSearch Dashboards Core repo removed xpack and packages only consumed by xpack. This might have caused some unforeseen circumstances where if a plugin was dependent on that package then their upgrade will fail unless they import the package directly. Plugins should be doing that already but just a warning since this came up already, for example here:

https://github.com/opensearch-project/sql/pull/141

**Comment by dblock** [comment]
Makes sense, want to give a PR a shot @kavilla?

**Comment by dblock** [comment]
I'm going to close this. @kavilla Feel free to reopen with more detail on what you'd like to happen, probably in a different repo.
