### ISSUE TITLE
List of Best Practices for Plugin Authors

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/opensearch-plugins#65]
Come up with an exhaustive list of best practices to be followed by the plugin developers. It should include design principles to be followed and also guidelines on the coding principles.

**Comment by saratvemulapalli** [comment]
@aditjind thanks for taking care of this. I see the changes are merged. Do you think we need anything else here?

**Comment by aditjind** [comment]
@saratvemulapalli I would like to keep this open as I believe it to be an ongoing effort. Any plugin developer who finds out about any best practice which needs to be followed can raise a PR and reference this Issue. WDYT?

**Comment by saratvemulapalli** [comment]
Ideally issues are open to take care of something actionable. We do not want to leave the issues open when there are no concrete asks. 

As we add new best practices, folks can create a new issue and link it to this one. 
I would recommend closing it now, if we don't have anything in mind to PR in near future.
