### ISSUE TITLE
OpenSearch API guidelines

### ISSUE THREAD

**Issue by vamshin** [opensearch-project/opensearch-plugins#71]
**Is your feature request related to a problem? Please describe.**
Every plugin comes up REST APIs and this keeps growing as the features are getting added. To make the API conventions standard across all the plugins with respect to naming/format etc, we need some guidelines and design principles that ensures uniformity of these APIs.

**Comment by dblock** [comment]
I moved this into opensearch-plugins, I think we should start here and not worry about core engine.

**Comment by saratvemulapalli** [comment]
@vamshin we have written up https://github.com/opensearch-project/opensearch-plugins/blob/main/CONVENTIONS.md, you think there's anything else we need to add, let us know.
