### ISSUE TITLE
[BUG] Link checker didn't detect the broken link for files in github repository

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/opensearch-plugins#90]
I found some broken links in [UPGRADING.md](https://github.com/opensearch-project/opensearch-plugins/blob/ece53bf9e93403272726eb6087ed98f9c821502b/UPGRADING.md#backwards-compatibility), they pointed to files in another github repository, whose locations have changed.
- https://github.com/opensearch-project/documentation-website/blob/main/docs/alerting/settings.md
- https://github.com/opensearch-project/documentation-website/blob/main/docs/ad/api.md

Seeing from the results of link checker runs, there is no error to show the broken links: 
https://github.com/opensearch-project/opensearch-plugins/actions/workflows/links.yml

I could create PR to change the above broken links to github permalink.

**Comment by AMoo-Miki** [comment]
I fixed the links in #100 but am wondering why the link-checker missed those bad links. I will try and figure it out.

**Comment by tlfeng** [comment]
> I fixed the links in #100 but am wondering why the link-checker missed those bad links. I will try and figure it out.

Hi Miki, thank you for fixing the links. I noticed the broken links for files in Github repo return the status 200, but not 4xx, but I didn't investigate further.

**Comment by dblock** [comment]
I'll close this. Since the host returns 200s link checker doesn't think they are broken.
